### PR TITLE
Raise syntax no longer accepts comma-separated arguments in python3

### PR DESCRIPTION
**Pull request by montiniz**

### CODE REVIEW

**Comment by galuszkak** [comment]
@montiniz could you add test for it? I suspect we didn't catch that before because there wasn't any test for this before.

**Comment by montiniz** [comment]
ready for review.
not sure why pypy fails. i'm not getting that on my pc.

**Comment by galuszkak** [comment]
Hi @montiniz . I've restarted tests. We will see how they will go.

**Comment by galuszkak** [comment]
Thanks @montiniz ! Tests are passing I've merged that.

**Pull request merged**
