### PR TITLE
django obsolete versions support removal

### PR DESCRIPTION
**Pull request by auvipy**
first pass

### CODE REVIEW

**Comment by galuszkak** [comment]
Hi @auvipy ! Thanks for PR! 
I'm afraid that this isn't so simple that we change only versions in travis and tox @auvipy. We need to upgrade whole app that passes all tests. This I think it's little bigger work than you expected, because it needs a little more time to dive in into code and then have working version with tests.

**Comment by auvipy** [comment]
@galuszkak I know, And I didn't expect to get things done like this!!! If you see my github activities I contributed on some projects so I am well aware of the upgrade stuff :D 

You can see I wrote first pass.

**Comment by galuszkak** [comment]
@auvipy I'm sorry didn't get that. Hope you resolve remaining problems :+1: :smile:

**Comment by auvipy** [comment]
yeah gonna start work sooon

**Comment by galuszkak** [comment]
closing in favor of #431

**Pull request closed without merging**
