### PR TITLE
Django 1.8 and 1.9 compatibility

### PR DESCRIPTION
**Pull request by arthur-wsw**

### CODE REVIEW

**Comment by arthur-wsw** [comment]
Here is a list of majors things i done here:

- Fix Django 1.8 issues and add 1.9 compatibility #425 #421
- Update all dependancies (DRF, floppyforms, filters, ...) #420 #408 #409
- Regenerate example project to make it django 1.9 compatible
- Update tox and travis and add flake8 #422 #411
- Rename AdminModel2Mixin to Admin2ModelMixin #347
- Add migrations
- Replace IPAddressField with GenericIPAddressField
- Fix password link in user admin
- Fix user logout on password change
- Fix tests
 - Move test models in separate models.py
 - Deleted date_format on floppyforms test because since 1.3 date_format is hardcoded to use %Y-%m-%d accorded to W3C HTML5 specification
 - Fix permission test by a new way to invalidate the users permission cache

**Comment by galuszkak** [comment]
Thanks @arthur-wsw for this awesome PR! That is big work here. I need more time to review but I will get back to You tomorrow.

**Comment by arthur-wsw** [comment]
Thanks @galuszkak,

Take your time, there is a lot of changes and if you have any question does not hesitate to contact me.

Currently i have some free time and would like to offer my help as an active maintainers of django-admin2, i think there is still a lot work that can be done

- Update default theme to bootstrap3
- Reviews all currently opened issue to see if there are still relevant
- Review documentation and write part that still have TODO
- Add compatibility for django 1.10 that has been release in alpha
- ...

**Comment by galuszkak** [comment]
@arthur-wsw this is OK. I'm merging that.

**Pull request merged**
